embed_assets: on

javascripts:
  workspace:
    - public/javascripts/common/*.js
    - public/javascripts/plugin/*.js
    - public/javascripts/bootstrap/bootstrap-modal.js
    - public/javascripts/bootstrap/bootstrap-alerts.js
    - public/javascripts/bootstrap/bootstrap-dropdown.js
    - public/javascripts/bootstrap/bootstrap-scrollspy.js
    - public/javascripts/bootstrap/bootstrap-buttons.js
    - public/javascripts/bootstrap/bootstrap-tabs.js
    - public/javascripts/bootstrap/bootstrap-twipsy.js
    - public/javascripts/bootstrap/bootstrap-popover.js
    - public/javascripts/esquire/*.js

stylesheets:
  workspace:
    - public/stylesheets/*.css